let i = 75;
console.log("Numeros");
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);
console.log(i);
i = (i + 1);